import '../models/book.dart';

final List<Book> allBooks = [
  Book(
    id: '1',
    title: 'Le petit prince',
    author: 'Antoine de Saint-Exupéry',
    genre: 'Fiction',
    imagePath: 'assets/images/petit_prince.jpg',
    description:
        'Le Petit Prince est un conte poétique qui explore les thèmes de l’innocence, de la solitude et de la perte.',
    clicks: 0,
    popularity: 100,
    dateAdded: DateTime(2023, 1, 1),
  ),
  Book(
    id: '2',
    title: '1984',
    author: 'George Orwell',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/1984.jpg',
    description:
        '1984 décrit une société totalitaire où chaque citoyen est surveillé en permanence.',
    clicks: 0,
    popularity: 95,
    dateAdded: DateTime(2023, 2, 1),
  ),
  Book(
    id: '3',
    title: 'Harry Potter à l’école des sorciers',
    author: 'J.K. Rowling',
    genre: 'Fantasy',
    imagePath: 'assets/images/harry_potter.jpg',
    description:
        'Premier tome de la saga Harry Potter, ce roman raconte l’entrée de Harry dans le monde magique.',
    clicks: 0,
    popularity: 120,
    dateAdded: DateTime(2023, 3, 1),
  ),
  Book(
    id: '4',
    title: 'Le Seigneur des Anneaux : La Communauté de l’Anneau',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    imagePath: 'assets/images/lotr_communaut.jpg',
    description:
        'Frodon Sacquet hérite d’un anneau mystérieux et entreprend un voyage périlleux avec une communauté de héros.',
    clicks: 0,
    popularity: 110,
    dateAdded: DateTime(2023, 4, 1),
  ),
  Book(
    id: '5',
    title: 'Dune',
    author: 'Frank Herbert',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/dune.jpg',
    description:
        'Considéré comme l’un des plus grands romans de science-fiction, Dune se déroule sur la planète Arrakis.',
    clicks: 0,
    popularity: 105,
    dateAdded: DateTime(2023, 5, 1),
  ),
  Book(
    id: '6',
    title: 'Le Hobbit',
    author: 'J.R.R. Tolkien',
    genre: 'Fantasy',
    imagePath: 'assets/images/le_hobbit.jpg',
    description:
        'Bilbo Bessac est entraîné dans une aventure avec treize nains pour reconquérir leur trésor gardé par le dragon Smaug.',
    clicks: 0,
    popularity: 102,
    dateAdded: DateTime(2023, 6, 1),
  ),
  Book(
    id: '7',
    title: 'L’Alchimiste',
    author: 'Paulo Coelho',
    genre: 'Roman Philosophique',
    imagePath: 'assets/images/l_alchimiste.jpg',
    description:
        'Santiago, un jeune berger, part à la recherche d’un trésor et découvre la sagesse universelle.',
    clicks: 0,
    popularity: 98,
    dateAdded: DateTime(2023, 7, 1),
  ),
  Book(
    id: '8',
    title: 'Fondation',
    author: 'Isaac Asimov',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/fondation.jpg',
    description:
        'Hari Seldon prédit la chute de l’Empire galactique et fonde la Fondation pour préserver le savoir humain.',
    clicks: 0,
    popularity: 97,
    dateAdded: DateTime(2023, 8, 1),
  ),
  Book(
    id: '9',
    title: 'Les Misérables',
    author: 'Victor Hugo',
    genre: 'Classique',
    imagePath: 'assets/images/les_miserables.jpg',
    description:
        'Jean Valjean, ancien forçat en quête de rédemption, est poursuivi par Javert dans une France tourmentée.',
    clicks: 0,
    popularity: 99,
    dateAdded: DateTime(2023, 9, 1),
  ),
  Book(
    id: '10',
    title: 'L’Assassin Royal : L’Apprenti Assassin',
    author: 'Robin Hobb',
    genre: 'Fantasy',
    imagePath: 'assets/images/assassin_royal1.jpg',
    description:
        'Fitz, fils illégitime d’un prince, est élevé dans l’ombre pour devenir un assassin royal.',
    clicks: 0,
    popularity: 88,
    dateAdded: DateTime(2023, 10, 1),
  ),
  Book(
    id: '11',
    title: 'Shining',
    author: 'Stephen King',
    genre: 'Horreur',
    imagePath: 'assets/images/shining.jpg',
    description:
        'Jack Torrance accepte un poste de gardien d’hiver dans un hôtel isolé et sombre dans la folie.',
    clicks: 0,
    popularity: 92,
    dateAdded: DateTime(2023, 11, 1),
  ),
  Book(
    id: '12',
    title: 'Autant en emporte le vent',
    author: 'Margaret Mitchell',
    genre: 'Romance Historique',
    imagePath: 'assets/images/autant_en_emporte_le_vent.jpg',
    description:
        'Scarlett O’Hara tente de survivre et de préserver sa famille pendant la guerre de Sécession.',
    clicks: 0,
    popularity: 90,
    dateAdded: DateTime(2023, 12, 1),
  ),
  Book(
    id: '13',
    title: 'Les Fleurs du mal',
    author: 'Charles Baudelaire',
    genre: 'Poésie',
    imagePath: 'assets/images/les_fleurs_du_mal.jpg',
    description:
        'Les Fleurs du mal explore la beauté, le spleen et la quête de l’idéal dans la poésie française.',
    clicks: 0,
    popularity: 85,
    dateAdded: DateTime(2024, 1, 1),
  ),
  Book(
    id: '14',
    title: 'La Voleuse de livres',
    author: 'Markus Zusak',
    genre: 'Drame',
    imagePath: 'assets/images/la_voleuse_de_livres.jpg',
    description:
        'L’histoire est narrée par la Mort et suit Liesel, une jeune fille allemande durant la Seconde Guerre mondiale.',
    clicks: 0,
    popularity: 93,
    dateAdded: DateTime(2024, 2, 1),
  ),
  Book(
    id: '15',
    title: 'Le Nom du Vent',
    author: 'Patrick Rothfuss',
    genre: 'Fantasy',
    imagePath: 'assets/images/le_nom_du_vent.jpg',
    description:
        'Kvothe raconte sa propre histoire : enfance tragique, passage à l’Université et aventures extraordinaires.',
    clicks: 0,
    popularity: 91,
    dateAdded: DateTime(2024, 3, 1),
  ),
  Book(
    id: '16',
    title: 'La Horde du Contrevent',
    author: 'Alain Damasio',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/la_horde_du_contrevent.jpg',
    description:
        'Une troupe d’élite lutte contre des vents violents dans une quête existentielle.',
    clicks: 0,
    popularity: 89,
    dateAdded: DateTime(2024, 4, 1),
  ),
  Book(
    id: '17',
    title: 'Neuromancien',
    author: 'William Gibson',
    genre: 'Cyberpunk',
    imagePath: 'assets/images/neuromancien.jpg',
    description:
        'Case, un hacker déchu, est recruté pour une mission impossible dans un futur cyberpunk.',
    clicks: 0,
    popularity: 87,
    dateAdded: DateTime(2024, 5, 1),
  ),
  Book(
    id: '18',
    title: 'Orgueil et Préjugés',
    author: 'Jane Austen',
    genre: 'Romance',
    imagePath: 'assets/images/orgueil_et_prejuges.jpg',
    description:
        'Elizabeth Bennet navigue dans les relations complexes de la société anglaise et rencontre Mr Darcy.',
    clicks: 0,
    popularity: 94,
    dateAdded: DateTime(2024, 6, 1),
  ),
  Book(
    id: '19',
    title: 'Le Parfum',
    author: 'Patrick Süskind',
    genre: 'Thriller Psychologique',
    imagePath: 'assets/images/le_parfum.jpg',
    description:
        'Jean-Baptiste Grenouille, né sans odeur, cherche à créer le parfum parfait et sombre dans l’obsession.',
    clicks: 0,
    popularity: 96,
    dateAdded: DateTime(2024, 7, 1),
  ),
  Book(
    id: '20',
    title: 'La Ferme des animaux',
    author: 'George Orwell',
    genre: 'Satire',
    imagePath: 'assets/images/la_ferme_des_animaux.jpg',
    description:
        'Une allégorie politique où des animaux de ferme renversent leur propriétaire humain pour instaurer un nouvel ordre.',
    clicks: 0,
    popularity: 86,
    dateAdded: DateTime(2024, 8, 1),
  ),
  Book(
    id: '21',
    title: 'Le Comte de Monte-Cristo',
    author: 'Alexandre Dumas',
    genre: 'Aventure',
    imagePath: 'assets/images/monte_cristo.jpg',
    description:
        'Edmond Dantès, injustement emprisonné, s'évade et revient se venger sous l'identité du mystérieux Comte de Monte-Cristo.',
    clicks: 0,
    popularity: 101,
    dateAdded: DateTime(2024, 9, 1),
  ),
  Book(
    id: '22',
    title: 'Cent ans de solitude',
    author: 'Gabriel García Márquez',
    genre: 'Réalisme Magique',
    imagePath: 'assets/images/cent_ans_de_solitude.jpg',
    description:
        'L'histoire de la famille Buendía à travers sept générations dans le village imaginaire de Macondo.',
    clicks: 0,
    popularity: 95,
    dateAdded: DateTime(2024, 10, 1),
  ),
  Book(
    id: '23',
    title: 'L'Étranger',
    author: 'Albert Camus',
    genre: 'Philosophique',
    imagePath: 'assets/images/l_etranger.jpg',
    description:
        'Meursault, un homme indifférent, commet un meurtre et affronte l'absurdité de l'existence lors de son procès.',
    clicks: 0,
    popularity: 88,
    dateAdded: DateTime(2024, 11, 1),
  ),
  Book(
    id: '24',
    title: 'Le Trône de Fer : Le Trône de Fer',
    author: 'George R.R. Martin',
    genre: 'Fantasy',
    imagePath: 'assets/images/trone_de_fer.jpg',
    description:
        'Dans le royaume de Westeros, plusieurs familles nobles se battent pour le contrôle du Trône de Fer.',
    clicks: 0,
    popularity: 115,
    dateAdded: DateTime(2024, 12, 1),
  ),
  Book(
    id: '25',
    title: 'Les Trois Mousquetaires',
    author: 'Alexandre Dumas',
    genre: 'Aventure',
    imagePath: 'assets/images/trois_mousquetaires.jpg',
    description:
        'D'Artagnan quitte la Gascogne pour Paris et s'allie à trois mousquetaires du roi dans des aventures palpitantes.',
    clicks: 0,
    popularity: 97,
    dateAdded: DateTime(2025, 1, 1),
  ),
  Book(
    id: '26',
    title: 'American Gods',
    author: 'Neil Gaiman',
    genre: 'Fantasy Urbaine',
    imagePath: 'assets/images/american_gods.jpg',
    description:
        'Shadow Moon se retrouve au cœur d'une guerre entre les anciens dieux et les nouvelles divinités de l'Amérique moderne.',
    clicks: 0,
    popularity: 93,
    dateAdded: DateTime(2025, 2, 1),
  ),
  Book(
    id: '27',
    title: 'Crime et Châtiment',
    author: 'Fiodor Dostoïevski',
    genre: 'Classique',
    imagePath: 'assets/images/crime_et_chatiment.jpg',
    description:
        'Raskolnikov, un étudiant pauvre, commet un meurtre et lutte avec la culpabilité et la rédemption.',
    clicks: 0,
    popularity: 91,
    dateAdded: DateTime(2025, 3, 1),
  ),
  Book(
    id: '28',
    title: 'Gatsby le Magnifique',
    author: 'F. Scott Fitzgerald',
    genre: 'Classique',
    imagePath: 'assets/images/gatsby.jpg',
    description:
        'Jay Gatsby, millionnaire mystérieux, organise des fêtes somptueuses pour reconquérir son amour perdu, Daisy.',
    clicks: 0,
    popularity: 94,
    dateAdded: DateTime(2025, 4, 1),
  ),
  Book(
    id: '29',
    title: 'La Route',
    author: 'Cormac McCarthy',
    genre: 'Post-Apocalyptique',
    imagePath: 'assets/images/la_route.jpg',
    description:
        'Un père et son fils traversent une Amérique dévastée, luttant pour leur survie dans un monde sans espoir.',
    clicks: 0,
    popularity: 89,
    dateAdded: DateTime(2025, 5, 1),
  ),
  Book(
    id: '30',
    title: 'La Passe-miroir : Les Fiancés de l'hiver',
    author: 'Christelle Dabos',
    genre: 'Fantasy',
    imagePath: 'assets/images/passe_miroir.jpg',
    description:
        'Ophélie, capable de lire le passé des objets et de traverser les miroirs, est fiancée contre son gré à Thorn.',
    clicks: 0,
    popularity: 87,
    dateAdded: DateTime(2025, 6, 1),
  ),
  Book(
    id: '31',
    title: 'Les Raisins de la colère',
    author: 'John Steinbeck',
    genre: 'Drame',
    imagePath: 'assets/images/raisins_de_la_colere.jpg',
    description:
        'La famille Joad fuit la misère du Dust Bowl pour chercher une vie meilleure en Californie pendant la Grande Dépression.',
    clicks: 0,
    popularity: 90,
    dateAdded: DateTime(2025, 7, 1),
  ),
  Book(
    id: '32',
    title: 'Fahrenheit 451',
    author: 'Ray Bradbury',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/fahrenheit_451.jpg',
    description:
        'Dans une société où les livres sont interdits, Guy Montag, un pompier chargé de les brûler, commence à remettre en question son rôle.',
    clicks: 0,
    popularity: 92,
    dateAdded: DateTime(2025, 8, 1),
  ),
  Book(
    id: '33',
    title: 'Beloved',
    author: 'Toni Morrison',
    genre: 'Drame',
    imagePath: 'assets/images/beloved.jpg',
    description:
        'Sethe, ancienne esclave, est hantée par le fantôme de sa fille décédée dans l'Ohio post-guerre de Sécession.',
    clicks: 0,
    popularity: 85,
    dateAdded: DateTime(2025, 9, 1),
  ),
  Book(
    id: '34',
    title: 'Le Maître et Marguerite',
    author: 'Mikhaïl Boulgakov',
    genre: 'Fantasy',
    imagePath: 'assets/images/maitre_et_marguerite.jpg',
    description:
        'Le diable arrive à Moscou et sème le chaos. Une histoire fascinante mêlant satire, amour et fantastique.',
    clicks: 0,
    popularity: 88,
    dateAdded: DateTime(2025, 10, 1),
  ),
  Book(
    id: '35',
    title: 'Le Vieil Homme et la Mer',
    author: 'Ernest Hemingway',
    genre: 'Classique',
    imagePath: 'assets/images/vieil_homme_et_la_mer.jpg',
    description:
        'Un vieux pêcheur cubain livre un combat épique contre un énorme marlin dans le Golfe du Mexique.',
    clicks: 0,
    popularity: 89,
    dateAdded: DateTime(2025, 11, 1),
  ),
  Book(
    id: '36',
    title: 'La Servante écarlate',
    author: 'Margaret Atwood',
    genre: 'Dystopie',
    imagePath: 'assets/images/servante_ecarlate.jpg',
    description:
        'Dans la République de Gilead, les femmes sont soumises à un régime totalitaire et réduites à leur fonction reproductrice.',
    clicks: 0,
    popularity: 98,
    dateAdded: DateTime(2025, 12, 1),
  ),
  Book(
    id: '37',
    title: 'Les Hauts de Hurlevent',
    author: 'Emily Brontë',
    genre: 'Romance',
    imagePath: 'assets/images/hurlevent.jpg',
    description:
        'Une histoire d'amour passionnée et destructrice entre Heathcliff et Catherine dans les landes anglaises.',
    clicks: 0,
    popularity: 86,
    dateAdded: DateTime(2026, 1, 1),
  ),
  Book(
    id: '38',
    title: 'Rebecca',
    author: 'Daphne du Maurier',
    genre: 'Thriller',
    imagePath: 'assets/images/rebecca.jpg',
    description:
        'Une jeune mariée arrive à Manderley et découvre que l'ombre de Rebecca, la première épouse de son mari, plane toujours.',
    clicks: 0,
    popularity: 91,
    dateAdded: DateTime(2026, 2, 1),
  ),
  Book(
    id: '39',
    title: 'Candide',
    author: 'Voltaire',
    genre: 'Satire',
    imagePath: 'assets/images/candide.jpg',
    description:
        'Candide traverse le monde et découvre que tout n'est pas pour le mieux dans le meilleur des mondes possibles.',
    clicks: 0,
    popularity: 84,
    dateAdded: DateTime(2026, 3, 1),
  ),
  Book(
    id: '40',
    title: 'Ne tirez pas sur l'oiseau moqueur',
    author: 'Harper Lee',
    genre: 'Drame',
    imagePath: 'assets/images/oiseau_moqueur.jpg',
    description:
        'Scout Finch raconte comment son père, avocat, défend un homme noir accusé à tort dans l'Alabama des années 1930.',
    clicks: 0,
    popularity: 96,
    dateAdded: DateTime(2026, 4, 1),
  ),
  Book(
    id: '41',
    title: 'La Nuit des temps',
    author: 'René Barjavel',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/nuit_des_temps.jpg',
    description:
        'Des scientifiques découvrent en Antarctique deux corps conservés depuis 900 000 ans, révélant une civilisation ancienne.',
    clicks: 0,
    popularity: 93,
    dateAdded: DateTime(2026, 5, 1),
  ),
  Book(
    id: '42',
    title: 'Dracula',
    author: 'Bram Stoker',
    genre: 'Horreur',
    imagePath: 'assets/images/dracula.jpg',
    description:
        'Le comte Dracula, vampire ancestral, quitte la Transylvanie pour l'Angleterre, semant la terreur sur son passage.',
    clicks: 0,
    popularity: 95,
    dateAdded: DateTime(2026, 6, 1),
  ),
  Book(
    id: '43',
    title: 'Moby Dick',
    author: 'Herman Melville',
    genre: 'Aventure',
    imagePath: 'assets/images/moby_dick.jpg',
    description:
        'Le capitaine Achab poursuit Moby Dick, la baleine blanche qui lui a arraché une jambe, dans une quête obsessionnelle.',
    clicks: 0,
    popularity: 87,
    dateAdded: DateTime(2026, 7, 1),
  ),
  Book(
    id: '44',
    title: 'La Métamorphose',
    author: 'Franz Kafka',
    genre: 'Absurde',
    imagePath: 'assets/images/metamorphose.jpg',
    description:
        'Gregor Samsa se réveille un matin transformé en un gigantesque insecte, bouleversant sa vie et celle de sa famille.',
    clicks: 0,
    popularity: 83,
    dateAdded: DateTime(2026, 8, 1),
  ),
  Book(
    id: '45',
    title: 'Les Chroniques martiennes',
    author: 'Ray Bradbury',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/chroniques_martiennes.jpg',
    description:
        'Une série de nouvelles racontant la colonisation de Mars par les humains et leurs rencontres avec les Martiens.',
    clicks: 0,
    popularity: 90,
    dateAdded: DateTime(2026, 9, 1),
  ),
  Book(
    id: '46',
    title: 'Le Portrait de Dorian Gray',
    author: 'Oscar Wilde',
    genre: 'Classique',
    imagePath: 'assets/images/dorian_gray.jpg',
    description:
        'Dorian Gray reste éternellement jeune tandis que son portrait vieillit et reflète la corruption de son âme.',
    clicks: 0,
    popularity: 92,
    dateAdded: DateTime(2026, 10, 1),
  ),
  Book(
    id: '47',
    title: 'La Couleur des sentiments',
    author: 'Kathryn Stockett',
    genre: 'Drame',
    imagePath: 'assets/images/couleur_des_sentiments.jpg',
    description:
        'Dans le Mississippi des années 1960, une jeune journaliste blanche recueille les témoignages de domestiques noires.',
    clicks: 0,
    popularity: 88,
    dateAdded: DateTime(2026, 11, 1),
  ),
  Book(
    id: '48',
    title: 'Solaris',
    author: 'Stanisław Lem',
    genre: 'Science-Fiction',
    imagePath: 'assets/images/solaris.jpg',
    description:
        'Sur la planète Solaris, un océan vivant crée des manifestations du passé des cosmonautes, révélant leurs tourments.',
    clicks: 0,
    popularity: 85,
    dateAdded: DateTime(2026, 12, 1),
  ),
  Book(
    id: '49',
    title: 'Les Piliers de la Terre',
    author: 'Ken Follett',
    genre: 'Roman Historique',
    imagePath: 'assets/images/piliers_de_la_terre.jpg',
    description:
        'L'histoire de la construction d'une cathédrale au XIIe siècle en Angleterre, entre ambitions, amours et trahisons.',
    clicks: 0,
    popularity: 99,
    dateAdded: DateTime(2027, 1, 1),
  ),
  Book(
    id: '50',
    title: 'La Mort d'Ivan Ilitch',
    author: 'Léon Tolstoï',
    genre: 'Philosophique',
    imagePath: 'assets/images/mort_ivan_ilitch.jpg',
    description:
        'Ivan Ilitch, juge respecté, affronte sa propre mort et remet en question le sens de son existence.',
    clicks: 0,
    popularity: 82,
    dateAdded: DateTime(2027, 2, 1),
  ),
];
